INSERT INTO status(id, code, description) VALUES(1, '0', 'موفق');
INSERT INTO status(id, code, description) VALUES(2, '400', 'درخواست نامعتبر');
INSERT INTO status(id, code, description) VALUES(3, '900', 'فایل ارسالی دارای مشکل میباشد');
INSERT INTO status(id, code, description) VALUES(4, '1', 'نام کاربری تکراری است');
INSERT INTO status(id, code, description) VALUES(5, '2', 'یوزر یافت نشد');
INSERT INTO status(id, code, description) VALUES(6, '3', 'پسورد اجباری است');
INSERT INTO status(id, code, description) VALUES(7, '4', 'عنوان درخواست اجباری است');
INSERT INTO status(id, code, description) VALUES(8, '5', 'درخواست یافت نشد');
INSERT INTO category(id, code, title) VALUES(1, '1', 'تشریفات');
INSERT INTO category(id, code, title) VALUES(2, '2', 'آرایشی بهداشتی');